pipeline:
  release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME%%-service}"
      tags: "${CI_COMMIT_TAG##v}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
      tag: v*
